apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp-container
          image: prsdocker123/devopsproject-1:latest
          ports:
            - containerPort: 80
